src/provider/bpmn/utils/EventDefinitionUtil.js, src/provider/zeebe/ZeebePropertiesProvider.js, src/provider/zeebe/properties/TimerEventDefinitionProps.js, src/provider/zeebe/properties/index.js, test/spec/provider/zeebe/TimerEventDefinitionProps.bpmn, test/spec/provider/zeebe/TimerEventDefinitionProps.spec.js, test/spec/provider/zeebe/ZeebePropertiesProvider.bpmn, test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js
closes #4
closes bpmn-io/properties-panel-next#67
=> feat(zeebePropertiesProvider): add timerEventDefinition Properties

package-lock.json, package.json, src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js
=> feat: add CamundaPlatformPropertiesProvider

karma.config.js, package-lock.json, package.json, src/entries/ReferenceSelect.js, src/provider/bpmn/BpmnPropertiesProvider.js, src/provider/bpmn/properties/DocumentationProps.js, src/provider/bpmn/properties/ErrorProps.js, src/provider/bpmn/properties/Executable.js, src/provider/bpmn/properties/Id.js, src/provider/bpmn/properties/MessageProps.js, src/provider/bpmn/properties/Name.js, src/provider/bpmn/properties/ProcessProps.js, src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/zeebe/ZeebePropertiesProvider.js, src/provider/zeebe/properties/ConditionProps.js, src/provider/zeebe/properties/FormProps.js, src/provider/zeebe/properties/Header.js, src/provider/zeebe/properties/InputOutputParameter.js, src/provider/zeebe/properties/MessageProps.js, src/provider/zeebe/properties/MultiInstanceProps.js, src/provider/zeebe/properties/OutputPropagationProps.js, src/provider/zeebe/properties/TargetProps.js, src/provider/zeebe/properties/TaskDefinitionProps.js, src/provider/zeebe/properties/TimerEventDefinitionProps.js, src/render/BpmnPropertiesPanel.js, src/render/BpmnPropertiesPanelRenderer.js, src/render/index.js, test/spec/PanelHeaderProvider.spec.js, test/spec/extension/ExamplePropertiesProvider.js
Related to bpmn-io/properties-panel#80
=> Use transpiled version of properties panel

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js
=> chore(camunda-platform): hide (empty) groups for now

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/VersionTagProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/VersionTagProps-collaboration.bpmn, test/spec/provider/camunda-platform/VersionTagProps-process.bpmn, test/spec/provider/camunda-platform/VersionTagProps.spec.js
=> feat(camunda-platform): add version tag property

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/CandidateStarterProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Collaboration.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/CandidateStarterProps-Collaboration.bpmn, test/spec/provider/camunda-platform/CandidateStarterProps-Process.bpmn, test/spec/provider/camunda-platform/CandidateStarterProps.spec.js
=> 12 add candidate starer group

test/spec/BpmnPropertiesPanelRenderer.spec.js
=> chore: fix start:platform testCase

package-lock.json, package.json, src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/ProcessVariablesProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Collaboration.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/ProcessVariablesProps-collaboration.bpmn, test/spec/provider/camunda-platform/ProcessVariablesProps-process.bpmn, test/spec/provider/camunda-platform/ProcessVariablesProps.spec.js
Closes #25
Note for the reviewer:
* this is a read-only list, it's not possible to (directly) add variables to this list and remove ones
* I placed the group to a more top position since it's an overview and more likely to see at a first position (assumption) => We can also keep with the alphabetical order
_single scope_
_multiple scopes_
=> feat(camunda-platform): add process variables group

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/ExtensionPropertiesProps.js, src/provider/camunda-platform/properties/ExtensionProperty.js, src/provider/camunda-platform/properties/FieldInjectionProps.js, src/provider/camunda-platform/properties/JobExecutionProps.js, src/provider/camunda-platform/properties/index.js, src/provider/camunda-platform/utils/ExtensionElementsUtil.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/ExtensionPropertiesProps.bpmn, test/spec/provider/camunda-platform/ExtensionPropertiesProps.spec.js, test/spec/provider/camunda-platform/ExtensionProperty.bpmn, test/spec/provider/camunda-platform/ExtensionProperty.spec.js, test/spec/provider/camunda-platform/FieldInjection.spec.js, test/spec/provider/camunda-platform/FieldInjectionProps.spec.js, test/spec/provider/camunda-platform/JobExecutionProps.spec.js
=> Extension Properties

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/ExternalTaskPriorityProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/ExternalTaskPriority-Collaboration.bpmn, test/spec/provider/camunda-platform/ExternalTaskPriority-Process.bpmn, test/spec/provider/camunda-platform/ExternalTaskPriorityProps.spec.js
=> feat(camundaPropertiesProvider): add externalTaskPriorityProps

README.md, src/render/BpmnPropertiesPanelRenderer.js, test/TestHelper.js, test/fixtures/simple.bpmn, test/spec/BpmnPropertiesPanelRenderer.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/2374
Rationale: https://github.com/camunda/camunda-modeler/issues/2374#issuecomment-883171791
=> refactor(render): split up attach + render concerns

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/UserAssignmentProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/UserAssignmentProps.bpmn, test/spec/provider/camunda-platform/UserAssignmentProps.spec.js
=> feat(camunda-platform): add user assignment group

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/InitiatorProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/InitiatorProps.bpmn, test/spec/provider/camunda-platform/InitiatorProps.spec.js
=> feat(camunda-platform): add start initiator group

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/DmnImplementationProps.js, src/provider/camunda-platform/properties/ImplementationProps.js, src/provider/camunda-platform/properties/ImplementationTypeProps.js, src/provider/camunda-platform/properties/index.js, src/provider/camunda-platform/utils/ImplementationTypeUtils.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/DmnImplementationProps.bpmn, test/spec/provider/camunda-platform/DmnImplementationProps.spec.js, test/spec/provider/camunda-platform/ImplementationProps.bpmn, test/spec/provider/camunda-platform/ImplementationProps.spec.js, test/spec/provider/camunda-platform/ImplementationTypeProps.spec.js
Closes #41
Also related: modeling behaviors https://github.com/camunda/camunda-bpmn-js/pull/34
=> feat(camunda-platform): add implementation group

package-lock.json, package.json, src/provider/camunda-platform/properties/ScriptProps.js
Related to https://github.com/bpmn-io/properties-panel/issues/87
Needs https://github.com/bpmn-io/properties-panel/pull/88 to be merged, released and integrated.
=> feat(script-props): set monospace

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/ErrorProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/ErrorProps.bpmn, test/spec/provider/camunda-platform/ErrorProps.spec.js
=> feat(camunda-platform): add error props

src/provider/camunda-platform/properties/ConditionProps.js, test/spec/provider/camunda-platform/ConditionProps.bpmn, test/spec/provider/camunda-platform/ConditionProps.spec.js
=> Conditional event

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/CallActivityProps.js, src/provider/camunda-platform/properties/CalledBpmnProps.js, src/provider/camunda-platform/properties/CalledCmmnProps.js, src/provider/camunda-platform/properties/DelegateVariableMappingProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CallActivityProps.bpmn, test/spec/provider/camunda-platform/CallActivityProps.spec.js
=> Implement call activity props

src/provider/zeebe/properties/HeaderProps.js, src/provider/zeebe/properties/InputProps.js, src/provider/zeebe/properties/OutputProps.js
Related to https://github.com/bpmn-io/properties-panel/issues/45
Requires https://github.com/bpmn-io/properties-panel/pull/91
=> feat: remove unnecessary classes

package-lock.json, package.json, src/provider/camunda-platform/properties/ExtensionPropertiesProps.js, src/provider/camunda-platform/properties/FieldInjection.js, src/provider/camunda-platform/properties/FieldInjectionProps.js, src/provider/camunda-platform/properties/ProcessVariablesProps.js, src/provider/zeebe/properties/HeaderProps.js, src/provider/zeebe/properties/InputProps.js, src/provider/zeebe/properties/OutputProps.js, test/spec/provider/camunda-platform/ExtensionPropertiesProps.spec.js, test/spec/provider/camunda-platform/ExtensionProperty.spec.js, test/spec/provider/camunda-platform/FieldInjection.spec.js, test/spec/provider/camunda-platform/FieldInjectionProps.spec.js, test/spec/provider/camunda-platform/ProcessVariablesProps.spec.js, test/spec/provider/zeebe/Header.spec.js, test/spec/provider/zeebe/HeaderProps.spec.js, test/spec/provider/zeebe/InputOutputParameter.spec.js, test/spec/provider/zeebe/InputProps.spec.js, test/spec/provider/zeebe/OutputProps.spec.js
Make list items unique per element.
Related to https://github.com/bpmn-io/properties-panel/issues/86
Depends on https://github.com/bpmn-io/properties-panel/pull/89 to merged, released + integrated
=> chore: update list item ids to be unique per element

CHANGELOG.md
=> chore(CHANGELOG): update to v0.2.0

src/provider/bpmn/BpmnPropertiesProvider.js, src/provider/bpmn/properties/CompensationProps.js, src/provider/bpmn/properties/index.js, src/provider/bpmn/utils/EventDefinitionUtil.js, test/spec/provider/bpmn/BpmnPropertiesProvider.bpmn, test/spec/provider/bpmn/BpmnPropertiesProvider.spec.js, test/spec/provider/bpmn/CompensationProps.bpmn, test/spec/provider/bpmn/CompensationProps.spec.js
Closes #78
Related to https://github.com/camunda/camunda-modeler/issues/2397
Note that for `waitForCompletion` the default is `true`.
=> feat(bpmn): add compensation props

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/FormKeyProps.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/FormKeyProps.bpmn, test/spec/provider/camunda-platform/FormKeyProps.spec.js
This adds the camunda:formKey
closes #91
=> feat(camundaProvider): add camunda:formKey props

package.json, src/provider/bpmn/BpmnPropertiesProvider.js, src/provider/bpmn/properties/MultiInstanceProps.js, src/provider/bpmn/properties/index.js, src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/zeebe/ZeebePropertiesProvider.js, src/provider/zeebe/properties/MultiInstanceProps.js, test/spec/BpmnPropertiesPanelRenderer.spec.js, test/spec/provider/bpmn/BpmnPropertiesProvider.bpmn, test/spec/provider/bpmn/BpmnPropertiesProvider.spec.js, test/spec/provider/bpmn/MultiInstanceProps.bpmn, test/spec/provider/bpmn/MultiInstanceProps.spec.js, test/spec/provider/zeebe/MultiInstanceProps.spec.js, test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js
closes #84
Note that this PR only includes the bpmn generic multiInstanceProps. Next step: I will follow-up with #85
=> 84 multiinstance props

package-lock.json, package.json, src/render/BpmnPropertiesPanel.js, src/render/BpmnPropertiesPanelRenderer.js, test/spec/BpmnPropertiesPanelRenderer.spec.js
* adjust to changes in implicit root ID
=> deps: update diagram-js to 7.4.0

package-lock.json, package.json
Support for nested lists & friends.
=> deps: update `@bpmn-io/properties-panel`

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/FormDataProps.js, src/provider/camunda-platform/properties/FormField.js, src/provider/camunda-platform/properties/FormFieldConstraint.js, src/provider/camunda-platform/properties/FormFieldProperty.js, src/provider/camunda-platform/properties/FormFieldValue.js, src/provider/camunda-platform/properties/index.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/FormDataProps.bpmn, test/spec/provider/camunda-platform/FormDataProps.spec.js, test/spec/provider/camunda-platform/FormField.bpmn, test/spec/provider/camunda-platform/FormField.spec.js, test/spec/provider/camunda-platform/FormFieldConstraint.spec.js, test/spec/provider/camunda-platform/FormFieldProperty.spec.js, test/spec/provider/camunda-platform/FormFieldValue.spec.js
closes #93
requires bpmn-io/properties-panel#93
=> 93 camunda form data props

src/provider/zeebe/ZeebePropertiesProvider.js, test/spec/provider/zeebe/ZeebePropertiesProvider.bpmn, test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js
Related to https://github.com/camunda/camunda-modeler/issues/2420
Before:
Now:
=> feat(cloud): remove message group for throw and end events

src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/ImplementationProps.js, src/provider/camunda-platform/properties/ListenerProps.js, src/provider/camunda-platform/properties/index.js, src/provider/camunda-platform/utils/ExtensionElementsUtil.js, src/provider/camunda-platform/utils/ImplementationTypeUtils.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/ListenerProps.bpmn, test/spec/provider/camunda-platform/ListenerProps.spec.js, test/spec/utils/ImplementationTypeUtils.spec.js
=> Migrate listener group

package-lock.json, package.json
=> chore: bump @bpmn-io/properties-panel to v0.4.1

src/provider/zeebe/properties/TimerProps.js
Closes #123 
Related to https://github.com/camunda/camunda-modeler/issues/2413
=> fix(zeebe): timer events documentation links

test/TestHelper.js, test/spec/provider/camunda-platform/FormDataProps.spec.js
This increases test speed significantly.
Closes #125
=> 125 improve test speed

package-lock.json, package.json, src/provider/bpmn/properties/ErrorProps.js, src/provider/bpmn/properties/EscalationProps.js, src/provider/bpmn/properties/MessageProps.js, src/provider/bpmn/properties/SignalProps.js, src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/Error.js, src/provider/camunda-platform/properties/ErrorsProps.js, src/provider/camunda-platform/properties/index.js, src/utils/ElementUtil.js, test/spec/BpmnPropertiesPanelRenderer.spec.js, test/spec/provider/bpmn/ErrorProps.spec.js, test/spec/provider/bpmn/MessageProps.spec.js, test/spec/provider/bpmn/SignalProps.spec.js, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider-Process.bpmn, test/spec/provider/camunda-platform/CamundaPlatformPropertiesProvider.spec.js, test/spec/provider/camunda-platform/Error.spec.js, test/spec/provider/camunda-platform/ErrorsProps.bpmn, test/spec/provider/camunda-platform/ErrorsProps.spec.js
* add _Errors_ group for external service tasks
* fix select empty state for global elements
=> Errors for External Service Tasks

src/provider/bpmn/properties/TimerProps.js, src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/ListenerProps.js, src/provider/camunda-platform/properties/index.js, src/provider/camunda-platform/utils/ImplementationTypeUtils.js, test/spec/provider/camunda-platform/ListenerProps.bpmn, test/spec/provider/camunda-platform/ListenerProps.spec.js, test/spec/utils/ImplementationTypeUtils.spec.js
=> Migrate task listener

src/provider/bpmn/properties/TimerProps.js, test/spec/provider/bpmn/TimerProps.spec.js
=> fix: timer props set event definition property

src/provider/bpmn/properties/DocumentationProps.js, src/provider/bpmn/properties/ErrorProps.js, src/provider/bpmn/properties/MessageProps.js, src/provider/bpmn/properties/ProcessProps.js, src/provider/camunda-platform/CamundaPlatformPropertiesProvider.js, src/provider/camunda-platform/properties/CandidateStarterProps.js, src/provider/camunda-platform/properties/ConditionProps.js, src/provider/camunda-platform/properties/DelegateVariableMappingProps.js, src/provider/camunda-platform/properties/DmnImplementationProps.js, src/provider/camunda-platform/properties/ErrorProps.js, src/provider/camunda-platform/properties/ImplementationProps.js, src/provider/camunda-platform/properties/ImplementationTypeProps.js, src/provider/camunda-platform/properties/JobExecutionProps.js, src/provider/camunda-platform/properties/ScriptTaskProps.js, src/provider/camunda-platform/properties/UserAssignmentProps.js, src/provider/camunda-platform/properties/VersionTagProps.js, src/provider/zeebe/ZeebePropertiesProvider.js, src/provider/zeebe/properties/ConditionProps.js, src/provider/zeebe/properties/FormProps.js, src/provider/zeebe/properties/InputOutputParameter.js, src/provider/zeebe/properties/MessageProps.js, src/provider/zeebe/properties/OutputPropagationProps.js, src/provider/zeebe/properties/TimerProps.js, test/spec/provider/camunda-platform/ImplementationTypeProps.spec.js
Closes #81
Cf. our [technical writing guide](https://github.com/camunda/camunda-modeler-design/blob/main/docs/technical-writing.md#capitalization)
Related to #90
=> chore: use sentence case for all labels

src/index.js, src/provider/element-templates/ElementTemplatesPropertiesProvider.js, src/provider/element-templates/Helper.js, src/provider/element-templates/properties/CustomProperties.js, src/provider/element-templates/properties/index.js, test/spec/BpmnPropertiesPanelRenderer.spec.js, test/spec/provider/element-templates/CreateHelper.spec.js, test/spec/provider/element-templates/ElementTemplates.spec.js, test/spec/provider/element-templates/ElementTemplatesLoader.spec.js, test/spec/provider/element-templates/ElementTemplatesPropertiesProvider.spec.js, test/spec/provider/element-templates/ReplaceBehavior.spec.js, test/spec/provider/element-templates/Validator.spec.js, test/spec/provider/element-templates/properties/CustomProperties.bpmn, test/spec/provider/element-templates/properties/CustomProperties.dropdown.bpmn, test/spec/provider/element-templates/properties/CustomProperties.json, test/spec/provider/element-templates/properties/CustomProperties.missing-types.bpmn, test/spec/provider/element-templates/properties/CustomProperties.missing-types.json, test/spec/provider/element-templates/properties/CustomProperties.spec.js
* adds entry for each element template property and scope
* tests copied 1:1
* validation only works for `String` entries as the properties panel doesn't support anything else
=> Element Templates Properties

src/provider/element-templates/ElementTemplatesPropertiesProvider.js, src/provider/element-templates/components/ElementTemplatesGroup.js, src/provider/element-templates/components/TemplateProps.js, src/provider/element-templates/components/index.js, test/spec/BpmnPropertiesPanelRenderer.spec.js, test/spec/provider/camunda-platform/FormDataProps.spec.js, test/spec/provider/element-templates/ElementTemplatesPropertiesProvider.spec.js, test/spec/provider/element-templates/TemplateProps.spec.js, test/spec/provider/element-templates/fixtures/complex.bpmn, test/spec/provider/element-templates/fixtures/complex.json, test/spec/provider/element-templates/fixtures/template-props.bpmn, test/spec/provider/element-templates/fixtures/template-props.json
- test: improve templates example
- feat(element-templates): add template information
Closes #145
Requires https://github.com/bpmn-io/bpmn-properties-panel/pull/146
=> Add template information

src/provider/element-templates/components/ElementTemplatesGroup.js, test/spec/provider/element-templates/ElementTemplates.bpmn, test/spec/provider/element-templates/ElementTemplates.spec.js, test/spec/provider/element-templates/ElementTemplatesPropertiesProvider.spec.js, test/spec/provider/element-templates/fixtures/simple.json
* Display update button only if an update is available.
* Update to the newest version of the template.
Closes #165
=> Correctly update template

src/provider/camunda-platform/properties/Error.js, src/provider/camunda-platform/properties/ErrorsProps.js, src/provider/element-templates/properties/ErrorProperties.js, test/spec/provider/camunda-platform/Error.spec.js, test/spec/provider/camunda-platform/ErrorsProps.bpmn, test/spec/provider/camunda-platform/ErrorsProps.spec.js, test/spec/provider/element-templates/properties/ErrorProperties.bpmn, test/spec/provider/element-templates/properties/ErrorProperties.json, test/spec/provider/element-templates/properties/ErrorProperties.spec.js
=> fix(element-templates): display proper error label

src/provider/element-templates/properties/CustomProperties.js, test/spec/provider/element-templates/properties/CustomProperties.description.bpmn, test/spec/provider/element-templates/properties/CustomProperties.description.json, test/spec/provider/element-templates/properties/CustomProperties.spec.js
=> feat(element-templates): display description of custom properties

package-lock.json, package.json, src/provider/element-templates/properties/CustomProperties.js, test/spec/provider/element-templates/properties/CustomProperties.editable.bpmn, test/spec/provider/element-templates/properties/CustomProperties.editable.json, test/spec/provider/element-templates/properties/CustomProperties.spec.js
=> Implement `editable`

test/spec/provider/element-templates/fixtures/complex.bpmn, test/spec/provider/element-templates/fixtures/complex.json
This makes sure we cover as many cases as possible
when running `npm run start:templates`.
Closes #179
=> test: improve templates example

src/provider/element-templates/ElementTemplatesPropertiesProvider.js, src/provider/element-templates/properties/CustomProperties.js, src/provider/element-templates/properties/InputProperties.js, src/provider/element-templates/properties/OutputProperties.js, test/spec/provider/element-templates/ElementTemplatesPropertiesProvider.bpmn, test/spec/provider/element-templates/ElementTemplatesPropertiesProvider.spec.js, test/spec/provider/element-templates/TemplateProps.spec.js, test/spec/provider/element-templates/fixtures/entries-visible.bpmn, test/spec/provider/element-templates/fixtures/entries-visible.json, test/spec/provider/element-templates/properties/ErrorProperties.spec.js, test/spec/provider/element-templates/properties/InputProperties.bpmn, test/spec/provider/element-templates/properties/InputProperties.spec.js, test/spec/provider/element-templates/properties/OutputProperties.bpmn, test/spec/provider/element-templates/properties/OutputProperties.json, test/spec/provider/element-templates/properties/OutputProperties.spec.js
Closes #156 
Built on top of https://github.com/bpmn-io/bpmn-properties-panel/pull/160
=> Implement entries visible

src/provider/element-templates/properties/InputProperties.js, src/provider/element-templates/properties/OutputProperties.js, test/spec/provider/element-templates/properties/InputProperties.bpmn, test/spec/provider/element-templates/properties/InputProperties.json, test/spec/provider/element-templates/properties/InputProperties.spec.js, test/spec/provider/element-templates/properties/OutputProperties.bpmn, test/spec/provider/element-templates/properties/OutputProperties.json, test/spec/provider/element-templates/properties/OutputProperties.spec.js
Closes #186
This will need to be tested via build artifacts:
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-linux-x64.tar.gz
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-mac.dmg
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-mac.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-win-ia32.zip
- https://camunda-modeler-on-demand.s3.eu-central-1.amazonaws.com/element-templates/camunda-modeler-element-templates-win-x64.zip
Build link: https://github.com/camunda/camunda-modeler/actions/runs/1480901812
=> chore: use single command to toggle input/output

CHANGELOG.md
=> chore(CHANGELOG): update to v0.4.0

src/provider/zeebe/properties/AssignmentDefinitionProps.js
silly mistake in latest commit
=> fix(CloudProvider): fix label for assignee

CHANGELOG.md, src/provider/zeebe/properties/FormProps.js, test/spec/provider/zeebe/Forms.spec.js
fixes upstream camunda/camunda-modeler#2579
=> chore: replace userTaskForm textField by textArea

CHANGELOG.md
=> chore(CHANGELOG): update to 0.5.1

src/provider/zeebe/properties/CalledDecisionProps.js
fixes upstream camunda/camunda-modeler#2585
=> fix(cloudProvider): fix dataMarker for calledDecision#decisionId

CHANGELOG.md, src/provider/zeebe/ZeebePropertiesProvider.js, src/provider/zeebe/utils/ZeebeServiceTaskUtil.js, test/spec/provider/zeebe/BusinessRuleImplementationProps.spec.js, test/spec/provider/zeebe/CalledDecisionProps.spec.js, test/spec/provider/zeebe/TaskDefinitionProps.spec.js, test/spec/provider/zeebe/ZeebePropertiesProvider.spec.js
related to camunda/camunda-modeler#2524
Back to old behavior:
=> chore(zeebeProvider): temporarily disable zeebe:calledDecision

package-lock.json, package.json
=> deps: update to `properties-panel@v0.8.1`

README.md
This adds an update that the repo is moved.
=> chore(README): add archiving info
